version: '3'
services:
  jenkins:
    image: "docker.io/komlevvladimir/jenkins-ci"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8080"
      - "50000:50000"