version: '3'
services:
  jenkins:
    image: "gitlab.btsd.kz:4567/smart-zhkh/jenkins-ci"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:8080"
      - "50000:50000"